### ISSUE TITLE
Feature Request: LDAP Authentication to web server

### ISSUE THREAD

**Issue by akitson-fu** [seatgeek/sixpack#250]
We've (we being First Utility,) forked your project with a view to adding authentication for access to the web server. We'll use LDAP (AD) for our purposes.  But before we start, I thought it would be helpful to gather the original author's input on how this might be best achieved. Do you have any preferences for library use for instance? Any other pointers?

Kind regards

**Comment by josegonzalez** [comment]
At SeatGeek, we do authentication outside of the application layer, at the server level. In our case, that is implemented in [nginx+lua](http://chairnerd.seatgeek.com/oauth-support-for-nginx-with-lua/). I'd recommend doing something similar to that, as it's highly unlikely that we'd merge any such feature since it's not the primary concern of this service.

The nice thing about doing this outside of sixpack is that you get to reuse auth for all backend admin panels, which is something we do with our authentication.

Does that make sense?

**Comment by chippyash** [comment]
Hi - yes - makes snes and we'll implement something similar.
